### ISSUE TITLE
Add doubly linked list

### ISSUE THREAD

**Issue by Aveek-Saha** [Aveek-Saha/js-data-structs#11]
## Doubly linked list -

**What will change** -
Add doubly linked lists

**Describe the solution you'd like**
You should be able to
- insert node at head
- insert node at tail
- insert at given index
- get node at given index
- delete from given index
- delete node at head
- delete node at tail
- display list as string

**Comment by truecryingdev** [comment]
Hi there. I can help with this. Can you assign me?

**Comment by Aveek-Saha** [comment]
Make sure you read the [contributing guidelines](https://github.com/Aveek-Saha/js-data-structs#contributing) before you start!

**Comment by truecryingdev** [comment]
Alright, working on it!
